### ISSUE TITLE
elementary_cli return (OS Error: The filename, directory name, or volume label syntax is incorrect. , errno = 123) error

### ISSUE THREAD

**Issue by pishguy** [Elementary-team/flutter-elementary#126]
when i try to create new module in project i get error

```console
D:\develop\flutter\bin\flutter.bat --no-color pub global run elementary_cli:elementary_tools generate module --path C:/Users/XXXXX/OneDrive/Desktop/develop/projects/flutter/XXXX/XXXXXX/lib/src/tabs/cart/screens --name promotion --create-subdirectory
Unhandled exception:
FileSystemException: Cannot copy file to 'C:\Users\XXXXX\AppData\Local\Pub\Cache\global_packages\elementary_cli\bin\..\lib\templates\widget.dart.tp', path = 'C:\Users\pishg\AppData\Local\Pub\Cache\hosted\pub.dev\elementary_cli-2.0.0\lib\templates\widget.dart.tp' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.copySync (dart:io/file_impl.dart:366:5)
#2      TemplateGeneratorCommand.copyTemplatesToScriptPath (package:elementary_cli/generate/generate.dart:123:14)
<asynchronous suspension>
#3      TemplateGeneratorCommand.defaultTemplateDirectoryPath (package:elementary_cli/generate/generate.dart:104:5)
<asynchronous suspension>
#4      TemplateGeneratorCommand.fillTemplates (package:elementary_cli/generate/generate.dart:68:43)
<asynchronous suspension>
#5      GenerateModuleCommand.run (package:elementary_cli/generate/generate_module.dart:83:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      main (file:///C:/Users/pishg/AppData/Local/Pub/Cache/hosted/pub.dev/elementary_cli-2.0.0/bin/elementary_tools.dart:17:5)
<asynchronous suspension>
```

**Comment by MbIXjkee** [comment]
Hi, maybe the absolute path is the problem here. Can you please try to run from the project folder with relative one?
